# Generated by Django 6.0.3 on 2026-03-25 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.marca')),
            ],
            options={
                'unique_together': {('nombre', 'marca')},
            },
        ),
        migrations.CreateModel(
            name='ModeloNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('marca', 'modelo')},
            },
        ),
        migrations.CreateModel(
            name='Compatibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.modelonotebook')),
            ],
            options={
                'verbose_name': 'Compatibilidad',
                'verbose_name_plural': 'Compatibilidades',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.modelo')),
                ('modelos_notebook', models.ManyToManyField(through='clientes.Compatibilidad', to='clientes.modelonotebook')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.tiporepuesto')),
            ],
        ),
        migrations.AddField(
            model_name='compatibilidad',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.repuesto'),
        ),
        migrations.AddField(
            model_name='marca',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.tiporepuesto'),
        ),
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equivalente', models.CharField(max_length=100)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias', to='clientes.repuesto')),
            ],
            options={
                'unique_together': {('repuesto', 'codigo_equivalente')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='compatibilidad',
            unique_together={('repuesto', 'modelo_notebook')},
        ),
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together={('nombre', 'tipo')},
        ),
    ]
