# Generated by Django 6.0.3 on 2026-03-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalenciaNuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equivalente', models.CharField(max_length=120)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.repuesto')),
            ],
            options={
                'unique_together': {('repuesto', 'codigo_equivalente')},
            },
        ),
        migrations.DeleteModel(
            name='Equivalencia',
        ),
    ]
