# Generated by Django 6.0.3 on 2026-03-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compatibilidad',
            options={'verbose_name': 'Compatibilidad', 'verbose_name_plural': 'Compatibilidades'},
        ),
    ]
