# Generated by Django 6.0.3 on 2026-03-23 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_compatibilidad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repuesto1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq1', to='clientes.repuesto')),
                ('repuesto2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq2', to='clientes.repuesto')),
            ],
        ),
    ]
