# Generated by Django 6.0.3 on 2026-03-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_repuesto_precio_compra_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equivalencia',
            unique_together={('repuesto1', 'repuesto2')},
        ),
    ]
